
import "./globals.css";
import Header from "@/components/Header";

import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css"; // keep your global styles here
import AppProvider from "@/redux/provider";
import MainLayout from "@/layouts/MainLayout";



export const metadata = {
  title: "Lele store",
  description: "Generated by create next app",
  keywords:
    "online Store",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    className="bg-gray-100 dark:bg-red-900">
      <body >
        
        <AppProvider>
          <MainLayout>
            <Header />
            { children }
           
          </MainLayout>
        </AppProvider>
      </body>
    </html>
  );
}
